spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/intelli_meet
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

app.upload.dir=/home/priyansh/Development/IntelliMeet/backend/uploads
app.aiservice.url=http://localhost:8000